# To enable this local profile, add "-Dspring.profiles.active=local"
#  to VM options in the project run configuration

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/"..."?useSSL=false
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        # Hibernate ddl auto (create, create-drop, validate, update)
        ddl-auto: validate

#logging:
#  level:
#    ROOT: DEBUG

keycloak:
  enabled: true
  auth-server-url: http://localhost:8082/auth
  realm: Realm...
  resource: clientId...
  public-client: true
  ssl-required: none
  principal-attribute: preferred_username
  credentials.secret: 52b3cc43-e..............
  use-resource-role-mappings: true
  bearer-only: true

# change the port on which the server is running
server:
  port: 8082

# Logs SQL queries in cosole, useful for debugging
# spring.jpa.show-sql=true

# Explicitely set logging level. Default is INFO
# Possible options are TRACE, DEBUG, INFO, WARN, ERROR, FATAL, and OFF.
# logging.level.root=TRACE

# Swagger documentation (default is true)
# enable.swagger.plugin=false