version: '3.5'
services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'demirev'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - demirev
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - my-db:/var/lib/mysql

networks:
  demirev:
    name: demirev
    driver: bridge
    
volumes:
  my-db:
